// Generated by EmDash on dev server start
// Do not edit manually

/// <reference types="emdash/locals" />

import type { ContentBylineCredit, PortableTextBlock } from "emdash";

export interface BlogPost {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  date: string;
  description?: string;
  content?: PortableTextBlock[];
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

export interface Work {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  description: string;
  technologies?: unknown;
  date: string;
  thumbnail: string;
  order?: number;
  content?: PortableTextBlock[];
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

declare module "emdash" {
  interface EmDashCollections {
    blog: BlogPost;
    works: Work;
  }
}