import { createHash } from 'node:crypto';
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { basename, dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const rootDir = resolve(__dirname, '..');
const publicFontDir = resolve(rootDir, 'public', 'fonts', 'zen-maru-gothic');
const generatedCssPath = resolve(publicFontDir, 'fonts.css');
const cacheDir = resolve(rootDir, '.cache');
const cachePath = resolve(cacheDir, 'zen-maru-gothic.json');
const FONT_CSS_URL = 'https://fonts.googleapis.com/css2?family=Zen+Maru+Gothic:wght@400;500;700&display=swap';
const FONT_CACHE_VERSION = 'zen-maru-gothic-400-500-700-v1';
const CHROME_UA = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36';

function hasErrorCode(error, code) {
  return typeof error === 'object'
    && error !== null
    && 'code' in error
    && error.code === code;
}

async function readJsonFile(path, fallback) {
  try {
    return JSON.parse(await readFile(path, 'utf8'));
  } catch (error) {
    if (hasErrorCode(error, 'ENOENT')) return fallback;
    throw error;
  }
}

function rewriteFontCss(css, fileMap) {
  let next = css.replaceAll('http://', 'https://');

  for (const [remoteUrl, localName] of fileMap) {
    next = next.replaceAll(remoteUrl, `/fonts/zen-maru-gothic/${localName}`);
  }

  return `/* generated by scripts/generate-fonts.mjs — do not edit */\n${next.trim()}\n`;
}

export async function generateMpFonts({ force = false } = {}) {
  const cache = await readJsonFile(cachePath, {});
  const existingCss = await readFile(generatedCssPath, 'utf8').catch(() => '');

  if (!force && cache.version === FONT_CACHE_VERSION && existingCss.includes('/fonts/zen-maru-gothic/')) {
    console.log('Skipped: Zen Maru Gothic (unchanged)');
    return;
  }

  const cssResponse = await fetch(FONT_CSS_URL, {
    headers: {
      'User-Agent': CHROME_UA,
      Accept: 'text/css,*/*;q=0.1',
    },
  });

  if (!cssResponse.ok) {
    throw new Error(`Google Fonts CSS: HTTP ${cssResponse.status}`);
  }

  const remoteCss = await cssResponse.text();
  const remoteUrls = [...new Set(
    [...remoteCss.matchAll(/url\((['"]?)(https:\/\/fonts\.gstatic\.com\/[^)'"]+)\1\)/g)]
      .map((match) => match[2]),
  )];

  if (remoteUrls.length === 0) {
    throw new Error('Google Fonts CSS did not contain woff2 urls.');
  }

  await mkdir(publicFontDir, { recursive: true });
  await mkdir(cacheDir, { recursive: true });

  const fileMap = new Map();

  await Promise.all(remoteUrls.map(async (remoteUrl) => {
    const parsed = new URL(remoteUrl);
    const localName = basename(parsed.pathname);
    const outputPath = resolve(publicFontDir, localName);
    const fontResponse = await fetch(remoteUrl, {
      headers: { 'User-Agent': CHROME_UA },
    });

    if (!fontResponse.ok) {
      throw new Error(`${localName}: HTTP ${fontResponse.status}`);
    }

    const buffer = Buffer.from(await fontResponse.arrayBuffer());
    await writeFile(outputPath, buffer);
    fileMap.set(remoteUrl, localName);
    console.log(`Generated: public/fonts/zen-maru-gothic/${localName}`);
  }));

  const localCss = rewriteFontCss(remoteCss, fileMap);
  await writeFile(generatedCssPath, localCss, 'utf8');
  await writeFile(cachePath, `${JSON.stringify({
    version: FONT_CACHE_VERSION,
    cssHash: createHash('sha256').update(localCss).digest('hex'),
    files: [...fileMap.values()],
  }, null, 2)}\n`, 'utf8');
  console.log(`Generated: public/fonts/zen-maru-gothic/fonts.css (${remoteUrls.length} files)`);
}
